backend:
  name: git-gateway
  branch: main
# Local testing
local_backend: true
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, ig]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
collections:
  - name: "staff"
    label: "Staff"
    label_singular: "Employee"
    folder: "src/content/staff/"
    preview_path: "/en/staff/{{slug}}"
    summary: "{{name}} ({{title}}) [{{function}}]"
    identifier_field: name
    create: true
    fields:
      - {label: "Public", name: "public", widget: "boolean", default: true, required: false}
      - {label: "Created", name: "date", widget: "datetime"}
      - {label: "Username", name: "username", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Functie", name: "function", widget: "select", options: ["boardmember", "advisor"], required: false}
      - {label: "Achtergrond Foto", name: "bgimage", widget: "image", media_folder: "/public/uploads/staff", public_folder: "/uploads/pages", default: /logo-192x192.png , required: false}
      - {label: "Profielfoto", name: "image", widget: "image", media_folder: "/public/uploads/staff", public_folder: "/uploads/pages", default: /logo-192x192.png }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Bio", name: "body", widget: "markdown"}
      - label: "Contact Information"
        name: "contact"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Telefoon", name: telephone, required: false}
          - {label: "Email", name: email, required: false}
          - {label: "Website", name: website, required: false}
      - label: "Social Media Links"
        name: "social"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Intagram Handle", name: instagram, required: false}
          - {label: "Twitter Handle", name: twitter, required: false}
          - {label: "Facebook Url", name: facebook, required: false}
          - {label: "Youtube Url", name: youtube, required: false}
          - {label: "LinkedIn Url", name: linkedin, required: false}

  - name: "partners"
    label: "Partners"
    label_singular: "Partner"
    folder: "src/content/partners/"
    preview_path: "/en/partners/{{name}}"
    summary: "{{name}} [{{type}}]"
    editor:
      preview: false
    identifier_field: name
    create: true
    fields:
      - {label: "Datum", name: "date", widget: "datetime", required: true, hidden: true}
      - {label: "Type", name: "type", widget: "select", options: ["individual", "group", "company", "ngo", "governmental institution", "school"], default: "individual"}
      - {label: "Naam", name: "name", widget: "string"}
      - {label: "Profielfoto", name: "image", widget: "image", media_folder: "/public/uploads/pages", public_folder: "/uploads/pages", default: /logo-192x192.png }
      - {label: "Shortbio", name: "body", widget: "markdown"}
      - label: "Contact Info"
        name: "contact"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Contactpersoon", name: contactpersoon, required: false}
          - {label: "Telefoon", name: telephone, required: false}
          - {label: "Email", name: email, required: false}
          - {label: "Website", name: website, required: false}



  - name: "pages"
    label: "Paginas"
    label_singular: "Pagina"
    folder: "src/content/pages/"
    preview_path: "/en/{{slug}}"
    i18n: true
    create: true
    fields:
      - {label: "Pubilcatie Datum", name: "date", widget: "datetime", i18n: duplicate}
      - {label: "Status", name: "status", widget: "select", options: ['published', 'archived'], required: false}
      - {label: "Auteur", name: author, widget: "relation", collection: "staff", value_field: "{{slug}}", display_fields: ["name", "title"], search_fields: ["name", "username", title ], multiple: false, i18n: duplicate}
      - {label: "Category", name: "category", widget: "select", options: ["subjects"], required: false}
      - {label: "Titel", name: "title", widget: "string", i18n: true}
      - {label: "SubTitle", name: "subtitle", widget: "string", required: false, i18n: true}
      - {label: "Foto", name: "image", widget: "image", media_folder: "/public/uploads/pages", public_folder: "/uploads/pages", required: false, i81n: duplicate}
      - {label: "Inhoud", name: "body", widget: "markdown", i18n: true}
      - {label: "Tags (SEO)", name: "tags", widget: "list", default: ["restoration"], required: false, i18n: true}
      - label: "Search Engine Optimization"
        name: "seo"
        widget: "object"
        collapsed: true
        i18n: true
        fields:
          - {label: "Foto Beschrijving", name: "imageAlt", required: false, i18n: true }
          - {label: "Title gebruikt voor Delen", name: "seoTitle", required: false, i18n: true }
          - {label: "Pagina Beschrijving", name: "description", widget: text, required: false, i18n: true }
      - {label: "Icon", name: "icon", widget: "string", default: "report-line", required: false, i81n: duplicate}
      - {label: "Icon Pack", name: "pack", widget: "string", default: "mdi", required: false, i81n: duplicate}
      - {label: "Menu Title", name: "shortTitle", widget: "string", required: false, i18n: true}
      - {label: "Menu volgorde", name: "index", widget: "number", required: false, i18n: true}
      - {label: "Layout", name: "layout", widget: "select", options: [{label: 'Page Layout', value: '../../../layouts/Page.astro'}, {label: 'Attachment Layout', value: '../../../layouts/Attachment.astro'}, {label: 'Contact Layout', value: '../../../layouts/Contact.astro'}], default: "../../../layouts/page.astro", required: false, i18n: duplicate}

  - label: "Site Settings"
    name: "settings"
    files:
      - label: "Site Info & Branding"
        name: "info"
        file: "src/content/settings/_info.yml"
        fields:
          - {label: "Site Title", name: title, widget: string}
          - {label: "Company Name", name: name, widget: string}
          - {label: "Site Description", name: description, widget: string}
          - {label: "Email Address", name: email, widget: string}
          - {label: Telephone, name: telephone, widget: string}
          - {label: "Bank Account", name: bankaccount, widget: string}
          - {label: "KVK Nummer", name: kvk, widget: string}

      - label: "Site Settings"
        name: "settings"
        file: "src/content/settings/_settings.yml"
        fields:
          - {label: "Default Theme", name: theme, widget: "select", options: ["dark", "light"], default: "dark"}

      - label: "Social Links"
        name: "social"
        file: "src/content/settings/_social.yml"
        fields:
        - {label: "Facebook Address", name: facebook, required: false}
        - {label: "Twitter Handle", name: twitter, required: false}
        - {label: "Instagram Handle", name: instagram, required: false}
        - {label: "Youtube Channel Address", name: youtube, required: false}
        - {label: "Tiktok Handle", name: tiktok, required: false}
        - {label: "VSKit Handle", name: vskit, required: false}
        - {label: "Audiomack Channel", name: audiomack, required: false}

      - label: "SEO Settings"
        name: "seo"
        file: "src/content/settings/_seo.yml"
        fields:
          - {label: "Facebook App ID", name: fbappid, widget: string}
          - {label: "Default Share Image", name: image ,widget: "image", required: false, media_folder: "/public/uploads/seo/", public_folder: "/uploads/seo/"}

    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    # meta: { path: { widget: string, label: "Path", index_file: "index" } }

media_folder: "/public/uploads"
public_folder: "/uploads"
search: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
show_preview_links: true

site_url: https://www.igborestoration.org
display_url: https://igborestoration.org
